name: PeachLib
version: '1.0.0-SNAPSHOT17'
main: de.peachbiscuit174.peachlib.PeachLib
api-version: '1.21'
authors: [ PeachBiscuit174 :D ]
description: PeachLib (PL)

commands:
  peachLibSettings:
    permission: "peachlib.admin.peachlibsettings.use"
    permission-message: "You are not allowed to use this Command!"
    description: "Admin Command"